$ ->
  isNameValid = false
  isPhoneValid = false
  isEmailValid = false

  toggleSubmit = ->
    if isEmailValid == true and isPhoneValid == true and isNameValid
      $('#submit').removeClass 'disabled'
      $('#submit').prop 'disabled', false
    else
      $('#submit').addClass 'disabled'
      $('#submit').prop 'disabled', true
    return


  $('form').submit (e) ->
    e.preventDefault()
    return

  Accordion = (el, multiple) ->
    @el = el or {}
    @multiple = multiple or false
    # Variables privadas
    links = @el.find('.link')
    # Evento
    links.on 'click', {
      el: @el
      multiple: @multiple
    }, @dropdown
    return

  Accordion::dropdown = (e) ->
    $el = e.data.el
    $this = $(this)
    $next = $this.next()
    $next.slideToggle()
    $this.parent().toggleClass 'open'
    if !e.data.multiple
      $el.find('.submenu').not($next).slideUp().parent().removeClass 'open'
    return

  accordion = new Accordion($('#accordion'), false)
  $('#Name').bind 'input propertychange', (e) ->
    isNameValid = e.target.validity.valid
    toggleSubmit()
    return
  $('#Phone').bind 'input propertychange', (e) ->
    isPhoneValid = e.target.validity.valid
    toggleSubmit()
    return
  $('#Email').bind 'input propertychange', (e) ->
    isEmailValid = e.target.validity.valid
    toggleSubmit()
    return
  $('#submit').click (e) ->
    user_name = $('#Name').val()
    user_email = $('#Email').val()
    user_phone = $('#Phone').val()
    console.log document.getElementById('Name').checkValidity()
    console.log document.getElementById('Email').checkValidity()
    console.log document.getElementById('Phone').checkValidity()
    console.log user_name, user_email, user_phone
    $.ajax(
      type: 'POST'
      url: "http://localhost:8080/user/edit/<%= user_found._id %>"
      data:
        name: user_name
        phone: user_phone
        email: user_email
      dataType: 'json'
      cache: false
      async: false).done (data) ->
      console.log data
      $.notify {
        icon: 'glyphicon glyphicon-warning-sign'
        title: 'Bootstrap notify<br>'
        message: 'Turning standard Bootstrap alerts into "notify" like notifications'
        url: 'https://github.com/mouse0270/bootstrap-notify'
        target: '_blank'
      },
        element: 'body'
        position: null
        type: 'info'
        allow_dismiss: true
        newest_on_top: false
        showProgressbar: false
        placement:
          from: 'top'
          align: 'right'
        offset: 20
        spacing: 10
        z_index: 1031
        delay: 5000
        timer: 1000
        url_target: '_blank'
        mouse_over: null
        animate:
          enter: 'animated fadeInDown'
          exit: 'animated fadeOutUp'
        onShow: null
        onShown: null
        onClose: null
        onClosed: null
        icon_type: 'class'
        template: '<div data-notify="container" class="col-xs-11 col-sm-3 alert alert-{0}" role="alert">' + '<button type="button" aria-hidden="true" class="close" data-notify="dismiss">×</button>' + '<span data-notify="icon"></span> ' + '<span data-notify="title">{1}</span> ' + '<span data-notify="message">{2}</span>' + '<div class="progress" data-notify="progressbar">' + '<div class="progress-bar progress-bar-{0}" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>' + '</div>' + '<a href="{3}" target="{4}" data-notify="url"></a>' + '</div>'
      return
    return
  return

# ---
# generated by js2coffee 2.2.0